---
- name: Installing dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
    update_cache: true

- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    enablerepo: https://download.docker.com/linux/fedora/docker-ce.repo
    state: present
    update_cache: true

- name: Enable Docker to start on boot
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started

- name: Enable containerd to start on boot
  ansible.builtin.systemd:
    name: containerd.service
    enabled: true
    state: started
